import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>turbo-storybook App content</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>turbo-storybook app content</h1>
        </div>
      </main>
    </>
  );
};

export default Home;
